from setuptools import setup, find_packages

setup(
    name="digital-humanities-narrative",
    version="0.1.0",
    description="数字人文叙事分析 - 从零散资料重构故事世界",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "spacy>=3.7",
        "transformers>=4.36",
        "torch>=2.1",
        "networkx>=3.2",
        "matplotlib>=3.8",
        "pyvis>=0.3",
        "python-dateutil>=2.8",
        "jieba>=0.42",
        "textblob>=0.17",
        "numpy>=1.24",
        "pandas>=2.0",
        "diskcache>=5.6",
        "pydantic>=2.0",
        "tenacity>=8.2",
        "openai>=1.0",
        "typer>=0.12",
        "rich>=13.0",
        "python-dotenv>=1.0",
        "streamlit>=1.30",
        "pyecharts>=2.0",
        "fastapi>=0.110",
        "uvicorn>=0.29",
        "chromadb>=0.4",
        "sentence-transformers>=2.6",
        "opencc>=1.1",
    ],
)
